
version: '2'
services:
  serve:
    build: .
    ports:
      - "8100:8100"
      - "35729:35729"
      - "53703:53703"
    volumes:
      - ./{NOME_APP}:/usr/src/app
    command: ionic serve --all -b
  install_node_modules:
    build: .
    volumes:
      - ./{NOME_APP}:/usr/src/app
    command: npm install
